name: Hippho CI

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check for Lint
        run: ./gradlew ktlint --continue
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Lint Check 실패
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }}
        if: failure()

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build
        run: ./gradlew assembleDebug
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Build
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }}
        if: always()